"""baseline schema

Revision ID: 07f53dc60e8c
Revises: 
Create Date: 2026-06-01 08:00:07.052005
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f53dc60e8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('credits_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('monthly_bots_used', sa.Integer(), nullable=False),
    sa.Column('monthly_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('notify_on_done', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_monthly_reset_at'), ['monthly_reset_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_wallet_address'), ['wallet_address'], unique=True)

    op.create_table('action_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('sub_user_id', sa.String(length=255), nullable=True),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_stage', sa.String(length=20), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index('ix_action_items_account_created', ['account_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_sub_user_id'), ['sub_user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('bot_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('sub_user_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meeting_url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('share_token_hash', sa.String(length=128), nullable=True),
    sa.Column('share_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_bot_snapshots_account_created', ['account_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_bot_snapshots_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index('ix_bot_snapshots_account_sub_user', ['account_id', 'sub_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_snapshots_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_snapshots_share_token_hash'), ['share_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_snapshots_sub_user_id'), ['sub_user_id'], unique=False)
        batch_op.create_index('ix_bot_snapshots_workspace_created', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_snapshots_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('sub_user_id', sa.String(length=255), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index('ix_idempotency_account_sub_key', ['account_id', 'sub_user_id', 'key'], unique=True)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_sub_user_id'), ['sub_user_id'], unique=False)

    op.create_table('meeting_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_url', sa.String(length=2048), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.Column('ai_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('transcript_word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_summaries_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_summaries_bot_id'), ['bot_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_meeting_summaries_created_at'), ['created_at'], unique=False)

    op.create_table('monitor_state',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('platform_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('retention_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('bot_retention_days', sa.Integer(), nullable=False),
    sa.Column('recording_retention_days', sa.Integer(), nullable=False),
    sa.Column('transcript_retention_days', sa.Integer(), nullable=False),
    sa.Column('anonymize_speakers', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retention_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_policies_account_id'), ['account_id'], unique=True)

    op.create_table('saml_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_slug', sa.String(length=100), nullable=False),
    sa.Column('org_name', sa.String(length=100), nullable=False),
    sa.Column('idp_metadata_url', sa.String(length=2048), nullable=True),
    sa.Column('idp_metadata_xml', sa.Text(), nullable=True),
    sa.Column('attribute_mapping', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('default_role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saml_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saml_configs_org_slug'), ['org_slug'], unique=True)

    op.create_table('unmatched_usdc_transfers',
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('from_address', sa.String(length=42), nullable=False),
    sa.Column('to_address', sa.String(length=42), nullable=False),
    sa.Column('amount_usdc', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tx_hash')
    )
    with op.batch_alter_table('unmatched_usdc_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unmatched_usdc_transfers_from_address'), ['from_address'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=False),
    sa.Column('signed_ts', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_next_retry_at'), ['next_retry_at'], unique=False)
        batch_op.create_index('ix_webhook_deliveries_retry', ['status', 'next_retry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_status'), ['status'], unique=False)
        batch_op.create_index('ix_webhook_deliveries_webhook_created', ['webhook_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_webhook_id'), ['webhook_id'], unique=False)

    op.create_table('webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_delivery_status', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhooks_is_active'), ['is_active'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=True),
    sa.Column('key_prefix', sa.String(length=16), nullable=True),
    sa.Column('key_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)

    op.create_table('calendar_feeds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ical_url', sa.String(length=2048), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bot_name', sa.String(length=100), nullable=True),
    sa.Column('auto_record', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_feeds_account_id'), ['account_id'], unique=False)

    op.create_table('credit_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_credit_tx_unique_ref', ['type', 'reference_id'], unique=True, sqlite_where=sa.text('reference_id IS NOT NULL'), postgresql_where=sa.text('reference_id IS NOT NULL'))

    op.create_table('integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_account_id'), ['account_id'], unique=False)

    op.create_table('keyword_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('webhook_url', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_alerts_account_id'), ['account_id'], unique=False)

    op.create_table('oauth_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_accounts_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_accounts_provider_user_id'), ['provider_user_id'], unique=False)

    op.create_table('stripe_topups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    with op.batch_alter_table('stripe_topups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stripe_topups_account_id'), ['account_id'], unique=False)

    op.create_table('support_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_keys_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('usdc_deposits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('deposit_address', sa.String(length=42), nullable=False),
    sa.Column('hd_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hd_index')
    )
    with op.batch_alter_table('usdc_deposits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usdc_deposits_account_id'), ['account_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_usdc_deposits_deposit_address'), ['deposit_address'], unique=True)

    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_account_id', sa.String(length=36), nullable=False),
    sa.Column('settings', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_owner_account_id'), ['owner_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspaces_slug'), ['slug'], unique=True)

    op.create_table('workspace_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_members_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_members_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_members_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_members_account_id'))

    op.drop_table('workspace_members')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_slug'))
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_account_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('usdc_deposits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usdc_deposits_deposit_address'))
        batch_op.drop_index(batch_op.f('ix_usdc_deposits_account_id'))

    op.drop_table('usdc_deposits')
    with op.batch_alter_table('support_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_support_keys_account_id'))

    op.drop_table('support_keys')
    with op.batch_alter_table('stripe_topups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stripe_topups_account_id'))

    op.drop_table('stripe_topups')
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_provider_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_account_id'))

    op.drop_table('oauth_accounts')
    with op.batch_alter_table('keyword_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_alerts_account_id'))

    op.drop_table('keyword_alerts')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_account_id'))

    op.drop_table('integrations')
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_credit_tx_unique_ref', sqlite_where=sa.text('reference_id IS NOT NULL'), postgresql_where=sa.text('reference_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_account_id'))

    op.drop_table('credit_transactions')
    with op.batch_alter_table('calendar_feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_feeds_account_id'))

    op.drop_table('calendar_feeds')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key'))
        batch_op.drop_index(batch_op.f('ix_api_keys_account_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_is_active'))
        batch_op.drop_index(batch_op.f('ix_webhooks_account_id'))

    op.drop_table('webhooks')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_webhook_id'))
        batch_op.drop_index('ix_webhook_deliveries_webhook_created')
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_status'))
        batch_op.drop_index('ix_webhook_deliveries_retry')
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_next_retry_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_created_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_bot_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('unmatched_usdc_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unmatched_usdc_transfers_from_address'))

    op.drop_table('unmatched_usdc_transfers')
    with op.batch_alter_table('saml_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saml_configs_org_slug'))

    op.drop_table('saml_configs')
    with op.batch_alter_table('retention_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_policies_account_id'))

    op.drop_table('retention_policies')
    op.drop_table('platform_config')
    op.drop_table('monitor_state')
    with op.batch_alter_table('meeting_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_summaries_created_at'))
        batch_op.drop_index(batch_op.f('ix_meeting_summaries_bot_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_summaries_account_id'))

    op.drop_table('meeting_summaries')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_sub_user_id'))
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_expires_at'))
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_account_id'))
        batch_op.drop_index('ix_idempotency_account_sub_key')

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('bot_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_snapshots_workspace_id'))
        batch_op.drop_index('ix_bot_snapshots_workspace_created')
        batch_op.drop_index(batch_op.f('ix_bot_snapshots_sub_user_id'))
        batch_op.drop_index(batch_op.f('ix_bot_snapshots_share_token_hash'))
        batch_op.drop_index(batch_op.f('ix_bot_snapshots_expires_at'))
        batch_op.drop_index('ix_bot_snapshots_account_sub_user')
        batch_op.drop_index('ix_bot_snapshots_account_status')
        batch_op.drop_index(batch_op.f('ix_bot_snapshots_account_id'))
        batch_op.drop_index('ix_bot_snapshots_account_created')

    op.drop_table('bot_snapshots')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_account_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_items_sub_user_id'))
        batch_op.drop_index(batch_op.f('ix_action_items_status'))
        batch_op.drop_index(batch_op.f('ix_action_items_bot_id'))
        batch_op.drop_index(batch_op.f('ix_action_items_account_id'))
        batch_op.drop_index('ix_action_items_account_created')

    op.drop_table('action_items')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_wallet_address'))
        batch_op.drop_index(batch_op.f('ix_accounts_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_monthly_reset_at'))
        batch_op.drop_index(batch_op.f('ix_accounts_email'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
